# Generated by Django 3.2.17 on 2023-02-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson',
            new_name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(default='select an Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
